package fi.vilpponen.mhr.ore;

import fi.vilpponen.mhr.Unlock;
import fi.vilpponen.mhr.UnlockState;
import java.util.HashMap;
import java.util.Map;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;

/**
 * The ores whose world generation can be turned off one at a time.
 *
 * <p>This is the whole per-ore API: {@link #generates()} and {@link #setGenerates(boolean)} for the
 * shop to call once it exists, and {@link #isSuppressed(BlockState)} for the worldgen mixin. An ore
 * is a set of blocks — the stone and deepslate variants generate from the same feature — so the
 * lookup is by block, not by feature.
 *
 * <p>Only generation is affected. Mining, recipes, loot and trading are untouched on purpose: the
 * design rule is that the world is incomplete, not that normal actions are blocked.
 */
public enum Ore {
	COAL(Unlock.COAL, Blocks.COAL_ORE, Blocks.DEEPSLATE_COAL_ORE),
	IRON(Unlock.IRON, Blocks.IRON_ORE, Blocks.DEEPSLATE_IRON_ORE),
	COPPER(Unlock.COPPER, Blocks.COPPER_ORE, Blocks.DEEPSLATE_COPPER_ORE),
	// Nether gold ore counts as gold: it is an ore of gold generated by the same ore feature.
	// Gilded blackstone is left alone — it is a chest-like gamble, not an ore vein.
	GOLD(Unlock.GOLD, Blocks.GOLD_ORE, Blocks.DEEPSLATE_GOLD_ORE, Blocks.NETHER_GOLD_ORE),
	REDSTONE(Unlock.REDSTONE, Blocks.REDSTONE_ORE, Blocks.DEEPSLATE_REDSTONE_ORE),
	LAPIS(Unlock.LAPIS, Blocks.LAPIS_ORE, Blocks.DEEPSLATE_LAPIS_ORE),
	DIAMOND(Unlock.DIAMOND, Blocks.DIAMOND_ORE, Blocks.DEEPSLATE_DIAMOND_ORE);

	private static final Map<Block, Ore> BY_BLOCK = new HashMap<>();

	static {
		for (Ore ore : values()) {
			for (Block block : ore.blocks) {
				BY_BLOCK.put(block, ore);
			}
		}
	}

	private final Unlock unlock;
	private final Block[] blocks;

	Ore(Unlock unlock, Block... blocks) {
		this.unlock = unlock;
		this.blocks = blocks;
	}

	public Unlock unlock() {
		return unlock;
	}

	/** Whether this ore currently generates in new chunks. */
	public boolean generates() {
		return UnlockState.get().isOwned(unlock);
	}

	/** Turn this ore's generation on or off. Applies to chunks generated from now on. */
	public void setGenerates(boolean generates) {
		UnlockState.get().set(unlock, generates);
	}

	/** The ore this block belongs to, or null if it is not one of ours. */
	public static Ore byBlock(Block block) {
		return BY_BLOCK.get(block);
	}

	/** Whether worldgen must not place this block right now. */
	public static boolean isSuppressed(BlockState state) {
		Ore ore = byBlock(state.getBlock());
		return ore != null && !ore.generates();
	}
}
